// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// OtherTestsColumns holds the columns for the "other_tests" table.
	OtherTestsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "test", Type: field.TypeEnum, Enums: []string{"c", "d"}},
	}
	// OtherTestsTable holds the schema information for the "other_tests" table.
	OtherTestsTable = &schema.Table{
		Name:       "other_tests",
		Columns:    OtherTestsColumns,
		PrimaryKey: []*schema.Column{OtherTestsColumns[0]},
	}
	// TestsColumns holds the columns for the "tests" table.
	TestsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "test", Type: field.TypeEnum, Enums: []string{"a", "b"}},
	}
	// TestsTable holds the schema information for the "tests" table.
	TestsTable = &schema.Table{
		Name:       "tests",
		Columns:    TestsColumns,
		PrimaryKey: []*schema.Column{TestsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		OtherTestsTable,
		TestsTable,
	}
)

func init() {
}
