// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nint8835/entgql-bug-repro/ent/othertest"
	"github.com/nint8835/entgql-bug-repro/ent/predicate"
)

// OtherTestQuery is the builder for querying OtherTest entities.
type OtherTestQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.OtherTest
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the OtherTestQuery builder.
func (otq *OtherTestQuery) Where(ps ...predicate.OtherTest) *OtherTestQuery {
	otq.predicates = append(otq.predicates, ps...)
	return otq
}

// Limit adds a limit step to the query.
func (otq *OtherTestQuery) Limit(limit int) *OtherTestQuery {
	otq.limit = &limit
	return otq
}

// Offset adds an offset step to the query.
func (otq *OtherTestQuery) Offset(offset int) *OtherTestQuery {
	otq.offset = &offset
	return otq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (otq *OtherTestQuery) Unique(unique bool) *OtherTestQuery {
	otq.unique = &unique
	return otq
}

// Order adds an order step to the query.
func (otq *OtherTestQuery) Order(o ...OrderFunc) *OtherTestQuery {
	otq.order = append(otq.order, o...)
	return otq
}

// First returns the first OtherTest entity from the query.
// Returns a *NotFoundError when no OtherTest was found.
func (otq *OtherTestQuery) First(ctx context.Context) (*OtherTest, error) {
	nodes, err := otq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{othertest.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (otq *OtherTestQuery) FirstX(ctx context.Context) *OtherTest {
	node, err := otq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first OtherTest ID from the query.
// Returns a *NotFoundError when no OtherTest ID was found.
func (otq *OtherTestQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = otq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{othertest.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (otq *OtherTestQuery) FirstIDX(ctx context.Context) int {
	id, err := otq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single OtherTest entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one OtherTest entity is not found.
// Returns a *NotFoundError when no OtherTest entities are found.
func (otq *OtherTestQuery) Only(ctx context.Context) (*OtherTest, error) {
	nodes, err := otq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{othertest.Label}
	default:
		return nil, &NotSingularError{othertest.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (otq *OtherTestQuery) OnlyX(ctx context.Context) *OtherTest {
	node, err := otq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only OtherTest ID in the query.
// Returns a *NotSingularError when exactly one OtherTest ID is not found.
// Returns a *NotFoundError when no entities are found.
func (otq *OtherTestQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = otq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{othertest.Label}
	default:
		err = &NotSingularError{othertest.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (otq *OtherTestQuery) OnlyIDX(ctx context.Context) int {
	id, err := otq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of OtherTests.
func (otq *OtherTestQuery) All(ctx context.Context) ([]*OtherTest, error) {
	if err := otq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return otq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (otq *OtherTestQuery) AllX(ctx context.Context) []*OtherTest {
	nodes, err := otq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of OtherTest IDs.
func (otq *OtherTestQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := otq.Select(othertest.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (otq *OtherTestQuery) IDsX(ctx context.Context) []int {
	ids, err := otq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (otq *OtherTestQuery) Count(ctx context.Context) (int, error) {
	if err := otq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return otq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (otq *OtherTestQuery) CountX(ctx context.Context) int {
	count, err := otq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (otq *OtherTestQuery) Exist(ctx context.Context) (bool, error) {
	if err := otq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return otq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (otq *OtherTestQuery) ExistX(ctx context.Context) bool {
	exist, err := otq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the OtherTestQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (otq *OtherTestQuery) Clone() *OtherTestQuery {
	if otq == nil {
		return nil
	}
	return &OtherTestQuery{
		config:     otq.config,
		limit:      otq.limit,
		offset:     otq.offset,
		order:      append([]OrderFunc{}, otq.order...),
		predicates: append([]predicate.OtherTest{}, otq.predicates...),
		// clone intermediate query.
		sql:  otq.sql.Clone(),
		path: otq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Test othertest.Test `json:"test,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.OtherTest.Query().
//		GroupBy(othertest.FieldTest).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (otq *OtherTestQuery) GroupBy(field string, fields ...string) *OtherTestGroupBy {
	group := &OtherTestGroupBy{config: otq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := otq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return otq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Test othertest.Test `json:"test,omitempty"`
//	}
//
//	client.OtherTest.Query().
//		Select(othertest.FieldTest).
//		Scan(ctx, &v)
//
func (otq *OtherTestQuery) Select(fields ...string) *OtherTestSelect {
	otq.fields = append(otq.fields, fields...)
	return &OtherTestSelect{OtherTestQuery: otq}
}

func (otq *OtherTestQuery) prepareQuery(ctx context.Context) error {
	for _, f := range otq.fields {
		if !othertest.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if otq.path != nil {
		prev, err := otq.path(ctx)
		if err != nil {
			return err
		}
		otq.sql = prev
	}
	return nil
}

func (otq *OtherTestQuery) sqlAll(ctx context.Context) ([]*OtherTest, error) {
	var (
		nodes = []*OtherTest{}
		_spec = otq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &OtherTest{config: otq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, otq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (otq *OtherTestQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := otq.querySpec()
	return sqlgraph.CountNodes(ctx, otq.driver, _spec)
}

func (otq *OtherTestQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := otq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (otq *OtherTestQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   othertest.Table,
			Columns: othertest.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: othertest.FieldID,
			},
		},
		From:   otq.sql,
		Unique: true,
	}
	if unique := otq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := otq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, othertest.FieldID)
		for i := range fields {
			if fields[i] != othertest.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := otq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := otq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := otq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := otq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (otq *OtherTestQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(otq.driver.Dialect())
	t1 := builder.Table(othertest.Table)
	columns := otq.fields
	if len(columns) == 0 {
		columns = othertest.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if otq.sql != nil {
		selector = otq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	for _, p := range otq.predicates {
		p(selector)
	}
	for _, p := range otq.order {
		p(selector)
	}
	if offset := otq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := otq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// OtherTestGroupBy is the group-by builder for OtherTest entities.
type OtherTestGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (otgb *OtherTestGroupBy) Aggregate(fns ...AggregateFunc) *OtherTestGroupBy {
	otgb.fns = append(otgb.fns, fns...)
	return otgb
}

// Scan applies the group-by query and scans the result into the given value.
func (otgb *OtherTestGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := otgb.path(ctx)
	if err != nil {
		return err
	}
	otgb.sql = query
	return otgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (otgb *OtherTestGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := otgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (otgb *OtherTestGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(otgb.fields) > 1 {
		return nil, errors.New("ent: OtherTestGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := otgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (otgb *OtherTestGroupBy) StringsX(ctx context.Context) []string {
	v, err := otgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (otgb *OtherTestGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = otgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{othertest.Label}
	default:
		err = fmt.Errorf("ent: OtherTestGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (otgb *OtherTestGroupBy) StringX(ctx context.Context) string {
	v, err := otgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (otgb *OtherTestGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(otgb.fields) > 1 {
		return nil, errors.New("ent: OtherTestGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := otgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (otgb *OtherTestGroupBy) IntsX(ctx context.Context) []int {
	v, err := otgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (otgb *OtherTestGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = otgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{othertest.Label}
	default:
		err = fmt.Errorf("ent: OtherTestGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (otgb *OtherTestGroupBy) IntX(ctx context.Context) int {
	v, err := otgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (otgb *OtherTestGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(otgb.fields) > 1 {
		return nil, errors.New("ent: OtherTestGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := otgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (otgb *OtherTestGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := otgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (otgb *OtherTestGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = otgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{othertest.Label}
	default:
		err = fmt.Errorf("ent: OtherTestGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (otgb *OtherTestGroupBy) Float64X(ctx context.Context) float64 {
	v, err := otgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (otgb *OtherTestGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(otgb.fields) > 1 {
		return nil, errors.New("ent: OtherTestGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := otgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (otgb *OtherTestGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := otgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (otgb *OtherTestGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = otgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{othertest.Label}
	default:
		err = fmt.Errorf("ent: OtherTestGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (otgb *OtherTestGroupBy) BoolX(ctx context.Context) bool {
	v, err := otgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (otgb *OtherTestGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range otgb.fields {
		if !othertest.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := otgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := otgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (otgb *OtherTestGroupBy) sqlQuery() *sql.Selector {
	selector := otgb.sql.Select()
	aggregation := make([]string, 0, len(otgb.fns))
	for _, fn := range otgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(otgb.fields)+len(otgb.fns))
		for _, f := range otgb.fields {
			columns = append(columns, selector.C(f))
		}
		for _, c := range aggregation {
			columns = append(columns, c)
		}
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(otgb.fields...)...)
}

// OtherTestSelect is the builder for selecting fields of OtherTest entities.
type OtherTestSelect struct {
	*OtherTestQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (ots *OtherTestSelect) Scan(ctx context.Context, v interface{}) error {
	if err := ots.prepareQuery(ctx); err != nil {
		return err
	}
	ots.sql = ots.OtherTestQuery.sqlQuery(ctx)
	return ots.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (ots *OtherTestSelect) ScanX(ctx context.Context, v interface{}) {
	if err := ots.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (ots *OtherTestSelect) Strings(ctx context.Context) ([]string, error) {
	if len(ots.fields) > 1 {
		return nil, errors.New("ent: OtherTestSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := ots.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (ots *OtherTestSelect) StringsX(ctx context.Context) []string {
	v, err := ots.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (ots *OtherTestSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = ots.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{othertest.Label}
	default:
		err = fmt.Errorf("ent: OtherTestSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (ots *OtherTestSelect) StringX(ctx context.Context) string {
	v, err := ots.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (ots *OtherTestSelect) Ints(ctx context.Context) ([]int, error) {
	if len(ots.fields) > 1 {
		return nil, errors.New("ent: OtherTestSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := ots.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (ots *OtherTestSelect) IntsX(ctx context.Context) []int {
	v, err := ots.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (ots *OtherTestSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = ots.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{othertest.Label}
	default:
		err = fmt.Errorf("ent: OtherTestSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (ots *OtherTestSelect) IntX(ctx context.Context) int {
	v, err := ots.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (ots *OtherTestSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(ots.fields) > 1 {
		return nil, errors.New("ent: OtherTestSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := ots.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (ots *OtherTestSelect) Float64sX(ctx context.Context) []float64 {
	v, err := ots.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (ots *OtherTestSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = ots.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{othertest.Label}
	default:
		err = fmt.Errorf("ent: OtherTestSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (ots *OtherTestSelect) Float64X(ctx context.Context) float64 {
	v, err := ots.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (ots *OtherTestSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(ots.fields) > 1 {
		return nil, errors.New("ent: OtherTestSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := ots.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (ots *OtherTestSelect) BoolsX(ctx context.Context) []bool {
	v, err := ots.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (ots *OtherTestSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = ots.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{othertest.Label}
	default:
		err = fmt.Errorf("ent: OtherTestSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (ots *OtherTestSelect) BoolX(ctx context.Context) bool {
	v, err := ots.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ots *OtherTestSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := ots.sql.Query()
	if err := ots.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
