// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nint8835/entgql-bug-repro/ent/othertest"
)

// OtherTestCreate is the builder for creating a OtherTest entity.
type OtherTestCreate struct {
	config
	mutation *OtherTestMutation
	hooks    []Hook
}

// SetTest sets the "test" field.
func (otc *OtherTestCreate) SetTest(o othertest.Test) *OtherTestCreate {
	otc.mutation.SetTest(o)
	return otc
}

// Mutation returns the OtherTestMutation object of the builder.
func (otc *OtherTestCreate) Mutation() *OtherTestMutation {
	return otc.mutation
}

// Save creates the OtherTest in the database.
func (otc *OtherTestCreate) Save(ctx context.Context) (*OtherTest, error) {
	var (
		err  error
		node *OtherTest
	)
	if len(otc.hooks) == 0 {
		if err = otc.check(); err != nil {
			return nil, err
		}
		node, err = otc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*OtherTestMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = otc.check(); err != nil {
				return nil, err
			}
			otc.mutation = mutation
			if node, err = otc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(otc.hooks) - 1; i >= 0; i-- {
			if otc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = otc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, otc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (otc *OtherTestCreate) SaveX(ctx context.Context) *OtherTest {
	v, err := otc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (otc *OtherTestCreate) Exec(ctx context.Context) error {
	_, err := otc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (otc *OtherTestCreate) ExecX(ctx context.Context) {
	if err := otc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (otc *OtherTestCreate) check() error {
	if _, ok := otc.mutation.Test(); !ok {
		return &ValidationError{Name: "test", err: errors.New(`ent: missing required field "test"`)}
	}
	if v, ok := otc.mutation.Test(); ok {
		if err := othertest.TestValidator(v); err != nil {
			return &ValidationError{Name: "test", err: fmt.Errorf(`ent: validator failed for field "test": %w`, err)}
		}
	}
	return nil
}

func (otc *OtherTestCreate) sqlSave(ctx context.Context) (*OtherTest, error) {
	_node, _spec := otc.createSpec()
	if err := sqlgraph.CreateNode(ctx, otc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (otc *OtherTestCreate) createSpec() (*OtherTest, *sqlgraph.CreateSpec) {
	var (
		_node = &OtherTest{config: otc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: othertest.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: othertest.FieldID,
			},
		}
	)
	if value, ok := otc.mutation.Test(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: othertest.FieldTest,
		})
		_node.Test = value
	}
	return _node, _spec
}

// OtherTestCreateBulk is the builder for creating many OtherTest entities in bulk.
type OtherTestCreateBulk struct {
	config
	builders []*OtherTestCreate
}

// Save creates the OtherTest entities in the database.
func (otcb *OtherTestCreateBulk) Save(ctx context.Context) ([]*OtherTest, error) {
	specs := make([]*sqlgraph.CreateSpec, len(otcb.builders))
	nodes := make([]*OtherTest, len(otcb.builders))
	mutators := make([]Mutator, len(otcb.builders))
	for i := range otcb.builders {
		func(i int, root context.Context) {
			builder := otcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OtherTestMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, otcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, otcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, otcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (otcb *OtherTestCreateBulk) SaveX(ctx context.Context) []*OtherTest {
	v, err := otcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (otcb *OtherTestCreateBulk) Exec(ctx context.Context) error {
	_, err := otcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (otcb *OtherTestCreateBulk) ExecX(ctx context.Context) {
	if err := otcb.Exec(ctx); err != nil {
		panic(err)
	}
}
