// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/base64"
	"errors"
	"fmt"
	"io"
	"strconv"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/99designs/gqlgen/graphql"
	"github.com/99designs/gqlgen/graphql/errcode"
	"github.com/nint8835/entgql-bug-repro/ent/othertest"
	"github.com/nint8835/entgql-bug-repro/ent/test"
	"github.com/vektah/gqlparser/v2/gqlerror"
	"github.com/vmihailenco/msgpack/v5"
)

// OrderDirection defines the directions in which to order a list of items.
type OrderDirection string

const (
	// OrderDirectionAsc specifies an ascending order.
	OrderDirectionAsc OrderDirection = "ASC"
	// OrderDirectionDesc specifies a descending order.
	OrderDirectionDesc OrderDirection = "DESC"
)

// Validate the order direction value.
func (o OrderDirection) Validate() error {
	if o != OrderDirectionAsc && o != OrderDirectionDesc {
		return fmt.Errorf("%s is not a valid OrderDirection", o)
	}
	return nil
}

// String implements fmt.Stringer interface.
func (o OrderDirection) String() string {
	return string(o)
}

// MarshalGQL implements graphql.Marshaler interface.
func (o OrderDirection) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(o.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (o *OrderDirection) UnmarshalGQL(val interface{}) error {
	str, ok := val.(string)
	if !ok {
		return fmt.Errorf("order direction %T must be a string", val)
	}
	*o = OrderDirection(str)
	return o.Validate()
}

func (o OrderDirection) reverse() OrderDirection {
	if o == OrderDirectionDesc {
		return OrderDirectionAsc
	}
	return OrderDirectionDesc
}

func (o OrderDirection) orderFunc(field string) OrderFunc {
	if o == OrderDirectionDesc {
		return Desc(field)
	}
	return Asc(field)
}

func cursorsToPredicates(direction OrderDirection, after, before *Cursor, field, idField string) []func(s *sql.Selector) {
	var predicates []func(s *sql.Selector)
	if after != nil {
		if after.Value != nil {
			var predicate func([]string, ...interface{}) *sql.Predicate
			if direction == OrderDirectionAsc {
				predicate = sql.CompositeGT
			} else {
				predicate = sql.CompositeLT
			}
			predicates = append(predicates, func(s *sql.Selector) {
				s.Where(predicate(
					s.Columns(field, idField),
					after.Value, after.ID,
				))
			})
		} else {
			var predicate func(string, interface{}) *sql.Predicate
			if direction == OrderDirectionAsc {
				predicate = sql.GT
			} else {
				predicate = sql.LT
			}
			predicates = append(predicates, func(s *sql.Selector) {
				s.Where(predicate(
					s.C(idField),
					after.ID,
				))
			})
		}
	}
	if before != nil {
		if before.Value != nil {
			var predicate func([]string, ...interface{}) *sql.Predicate
			if direction == OrderDirectionAsc {
				predicate = sql.CompositeLT
			} else {
				predicate = sql.CompositeGT
			}
			predicates = append(predicates, func(s *sql.Selector) {
				s.Where(predicate(
					s.Columns(field, idField),
					before.Value, before.ID,
				))
			})
		} else {
			var predicate func(string, interface{}) *sql.Predicate
			if direction == OrderDirectionAsc {
				predicate = sql.LT
			} else {
				predicate = sql.GT
			}
			predicates = append(predicates, func(s *sql.Selector) {
				s.Where(predicate(
					s.C(idField),
					before.ID,
				))
			})
		}
	}
	return predicates
}

// PageInfo of a connection type.
type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *Cursor `json:"startCursor"`
	EndCursor       *Cursor `json:"endCursor"`
}

// Cursor of an edge type.
type Cursor struct {
	ID    int   `msgpack:"i"`
	Value Value `msgpack:"v,omitempty"`
}

// MarshalGQL implements graphql.Marshaler interface.
func (c Cursor) MarshalGQL(w io.Writer) {
	quote := []byte{'"'}
	w.Write(quote)
	defer w.Write(quote)
	wc := base64.NewEncoder(base64.RawStdEncoding, w)
	defer wc.Close()
	_ = msgpack.NewEncoder(wc).Encode(c)
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (c *Cursor) UnmarshalGQL(v interface{}) error {
	s, ok := v.(string)
	if !ok {
		return fmt.Errorf("%T is not a string", v)
	}
	if err := msgpack.NewDecoder(
		base64.NewDecoder(
			base64.RawStdEncoding,
			strings.NewReader(s),
		),
	).Decode(c); err != nil {
		return fmt.Errorf("cannot decode cursor: %w", err)
	}
	return nil
}

const errInvalidPagination = "INVALID_PAGINATION"

func validateFirstLast(first, last *int) (err *gqlerror.Error) {
	switch {
	case first != nil && last != nil:
		err = &gqlerror.Error{
			Message: "Passing both `first` and `last` to paginate a connection is not supported.",
		}
	case first != nil && *first < 0:
		err = &gqlerror.Error{
			Message: "`first` on a connection cannot be less than zero.",
		}
		errcode.Set(err, errInvalidPagination)
	case last != nil && *last < 0:
		err = &gqlerror.Error{
			Message: "`last` on a connection cannot be less than zero.",
		}
		errcode.Set(err, errInvalidPagination)
	}
	return err
}

func getCollectedField(ctx context.Context, path ...string) *graphql.CollectedField {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return nil
	}
	oc := graphql.GetOperationContext(ctx)
	field := fc.Field

walk:
	for _, name := range path {
		for _, f := range graphql.CollectFields(oc, field.Selections, nil) {
			if f.Name == name {
				field = f
				continue walk
			}
		}
		return nil
	}
	return &field
}

func hasCollectedField(ctx context.Context, path ...string) bool {
	if graphql.GetFieldContext(ctx) == nil {
		return true
	}
	return getCollectedField(ctx, path...) != nil
}

const (
	edgesField      = "edges"
	nodeField       = "node"
	pageInfoField   = "pageInfo"
	totalCountField = "totalCount"
)

// OtherTestEdge is the edge representation of OtherTest.
type OtherTestEdge struct {
	Node   *OtherTest `json:"node"`
	Cursor Cursor     `json:"cursor"`
}

// OtherTestConnection is the connection containing edges to OtherTest.
type OtherTestConnection struct {
	Edges      []*OtherTestEdge `json:"edges"`
	PageInfo   PageInfo         `json:"pageInfo"`
	TotalCount int              `json:"totalCount"`
}

// OtherTestPaginateOption enables pagination customization.
type OtherTestPaginateOption func(*otherTestPager) error

// WithOtherTestOrder configures pagination ordering.
func WithOtherTestOrder(order *OtherTestOrder) OtherTestPaginateOption {
	if order == nil {
		order = DefaultOtherTestOrder
	}
	o := *order
	return func(pager *otherTestPager) error {
		if err := o.Direction.Validate(); err != nil {
			return err
		}
		if o.Field == nil {
			o.Field = DefaultOtherTestOrder.Field
		}
		pager.order = &o
		return nil
	}
}

// WithOtherTestFilter configures pagination filter.
func WithOtherTestFilter(filter func(*OtherTestQuery) (*OtherTestQuery, error)) OtherTestPaginateOption {
	return func(pager *otherTestPager) error {
		if filter == nil {
			return errors.New("OtherTestQuery filter cannot be nil")
		}
		pager.filter = filter
		return nil
	}
}

type otherTestPager struct {
	order  *OtherTestOrder
	filter func(*OtherTestQuery) (*OtherTestQuery, error)
}

func newOtherTestPager(opts []OtherTestPaginateOption) (*otherTestPager, error) {
	pager := &otherTestPager{}
	for _, opt := range opts {
		if err := opt(pager); err != nil {
			return nil, err
		}
	}
	if pager.order == nil {
		pager.order = DefaultOtherTestOrder
	}
	return pager, nil
}

func (p *otherTestPager) applyFilter(query *OtherTestQuery) (*OtherTestQuery, error) {
	if p.filter != nil {
		return p.filter(query)
	}
	return query, nil
}

func (p *otherTestPager) toCursor(ot *OtherTest) Cursor {
	return p.order.Field.toCursor(ot)
}

func (p *otherTestPager) applyCursors(query *OtherTestQuery, after, before *Cursor) *OtherTestQuery {
	for _, predicate := range cursorsToPredicates(
		p.order.Direction, after, before,
		p.order.Field.field, DefaultOtherTestOrder.Field.field,
	) {
		query = query.Where(predicate)
	}
	return query
}

func (p *otherTestPager) applyOrder(query *OtherTestQuery, reverse bool) *OtherTestQuery {
	direction := p.order.Direction
	if reverse {
		direction = direction.reverse()
	}
	query = query.Order(direction.orderFunc(p.order.Field.field))
	if p.order.Field != DefaultOtherTestOrder.Field {
		query = query.Order(direction.orderFunc(DefaultOtherTestOrder.Field.field))
	}
	return query
}

// Paginate executes the query and returns a relay based cursor connection to OtherTest.
func (ot *OtherTestQuery) Paginate(
	ctx context.Context, after *Cursor, first *int,
	before *Cursor, last *int, opts ...OtherTestPaginateOption,
) (*OtherTestConnection, error) {
	if err := validateFirstLast(first, last); err != nil {
		return nil, err
	}
	pager, err := newOtherTestPager(opts)
	if err != nil {
		return nil, err
	}

	if ot, err = pager.applyFilter(ot); err != nil {
		return nil, err
	}

	conn := &OtherTestConnection{Edges: []*OtherTestEdge{}}
	if !hasCollectedField(ctx, edgesField) || first != nil && *first == 0 || last != nil && *last == 0 {
		if hasCollectedField(ctx, totalCountField) ||
			hasCollectedField(ctx, pageInfoField) {
			count, err := ot.Count(ctx)
			if err != nil {
				return nil, err
			}
			conn.TotalCount = count
			conn.PageInfo.HasNextPage = first != nil && count > 0
			conn.PageInfo.HasPreviousPage = last != nil && count > 0
		}
		return conn, nil
	}

	if (after != nil || first != nil || before != nil || last != nil) && hasCollectedField(ctx, totalCountField) {
		count, err := ot.Clone().Count(ctx)
		if err != nil {
			return nil, err
		}
		conn.TotalCount = count
	}

	ot = pager.applyCursors(ot, after, before)
	ot = pager.applyOrder(ot, last != nil)
	var limit int
	if first != nil {
		limit = *first + 1
	} else if last != nil {
		limit = *last + 1
	}
	if limit > 0 {
		ot = ot.Limit(limit)
	}

	if field := getCollectedField(ctx, edgesField, nodeField); field != nil {
		ot = ot.collectField(graphql.GetOperationContext(ctx), *field)
	}

	nodes, err := ot.All(ctx)
	if err != nil || len(nodes) == 0 {
		return conn, err
	}

	if len(nodes) == limit {
		conn.PageInfo.HasNextPage = first != nil
		conn.PageInfo.HasPreviousPage = last != nil
		nodes = nodes[:len(nodes)-1]
	}

	var nodeAt func(int) *OtherTest
	if last != nil {
		n := len(nodes) - 1
		nodeAt = func(i int) *OtherTest {
			return nodes[n-i]
		}
	} else {
		nodeAt = func(i int) *OtherTest {
			return nodes[i]
		}
	}

	conn.Edges = make([]*OtherTestEdge, len(nodes))
	for i := range nodes {
		node := nodeAt(i)
		conn.Edges[i] = &OtherTestEdge{
			Node:   node,
			Cursor: pager.toCursor(node),
		}
	}

	conn.PageInfo.StartCursor = &conn.Edges[0].Cursor
	conn.PageInfo.EndCursor = &conn.Edges[len(conn.Edges)-1].Cursor
	if conn.TotalCount == 0 {
		conn.TotalCount = len(nodes)
	}

	return conn, nil
}

// OtherTestOrderField defines the ordering field of OtherTest.
type OtherTestOrderField struct {
	field    string
	toCursor func(*OtherTest) Cursor
}

// OtherTestOrder defines the ordering of OtherTest.
type OtherTestOrder struct {
	Direction OrderDirection       `json:"direction"`
	Field     *OtherTestOrderField `json:"field"`
}

// DefaultOtherTestOrder is the default ordering of OtherTest.
var DefaultOtherTestOrder = &OtherTestOrder{
	Direction: OrderDirectionAsc,
	Field: &OtherTestOrderField{
		field: othertest.FieldID,
		toCursor: func(ot *OtherTest) Cursor {
			return Cursor{ID: ot.ID}
		},
	},
}

// ToEdge converts OtherTest into OtherTestEdge.
func (ot *OtherTest) ToEdge(order *OtherTestOrder) *OtherTestEdge {
	if order == nil {
		order = DefaultOtherTestOrder
	}
	return &OtherTestEdge{
		Node:   ot,
		Cursor: order.Field.toCursor(ot),
	}
}

// TestEdge is the edge representation of Test.
type TestEdge struct {
	Node   *Test  `json:"node"`
	Cursor Cursor `json:"cursor"`
}

// TestConnection is the connection containing edges to Test.
type TestConnection struct {
	Edges      []*TestEdge `json:"edges"`
	PageInfo   PageInfo    `json:"pageInfo"`
	TotalCount int         `json:"totalCount"`
}

// TestPaginateOption enables pagination customization.
type TestPaginateOption func(*testPager) error

// WithTestOrder configures pagination ordering.
func WithTestOrder(order *TestOrder) TestPaginateOption {
	if order == nil {
		order = DefaultTestOrder
	}
	o := *order
	return func(pager *testPager) error {
		if err := o.Direction.Validate(); err != nil {
			return err
		}
		if o.Field == nil {
			o.Field = DefaultTestOrder.Field
		}
		pager.order = &o
		return nil
	}
}

// WithTestFilter configures pagination filter.
func WithTestFilter(filter func(*TestQuery) (*TestQuery, error)) TestPaginateOption {
	return func(pager *testPager) error {
		if filter == nil {
			return errors.New("TestQuery filter cannot be nil")
		}
		pager.filter = filter
		return nil
	}
}

type testPager struct {
	order  *TestOrder
	filter func(*TestQuery) (*TestQuery, error)
}

func newTestPager(opts []TestPaginateOption) (*testPager, error) {
	pager := &testPager{}
	for _, opt := range opts {
		if err := opt(pager); err != nil {
			return nil, err
		}
	}
	if pager.order == nil {
		pager.order = DefaultTestOrder
	}
	return pager, nil
}

func (p *testPager) applyFilter(query *TestQuery) (*TestQuery, error) {
	if p.filter != nil {
		return p.filter(query)
	}
	return query, nil
}

func (p *testPager) toCursor(t *Test) Cursor {
	return p.order.Field.toCursor(t)
}

func (p *testPager) applyCursors(query *TestQuery, after, before *Cursor) *TestQuery {
	for _, predicate := range cursorsToPredicates(
		p.order.Direction, after, before,
		p.order.Field.field, DefaultTestOrder.Field.field,
	) {
		query = query.Where(predicate)
	}
	return query
}

func (p *testPager) applyOrder(query *TestQuery, reverse bool) *TestQuery {
	direction := p.order.Direction
	if reverse {
		direction = direction.reverse()
	}
	query = query.Order(direction.orderFunc(p.order.Field.field))
	if p.order.Field != DefaultTestOrder.Field {
		query = query.Order(direction.orderFunc(DefaultTestOrder.Field.field))
	}
	return query
}

// Paginate executes the query and returns a relay based cursor connection to Test.
func (t *TestQuery) Paginate(
	ctx context.Context, after *Cursor, first *int,
	before *Cursor, last *int, opts ...TestPaginateOption,
) (*TestConnection, error) {
	if err := validateFirstLast(first, last); err != nil {
		return nil, err
	}
	pager, err := newTestPager(opts)
	if err != nil {
		return nil, err
	}

	if t, err = pager.applyFilter(t); err != nil {
		return nil, err
	}

	conn := &TestConnection{Edges: []*TestEdge{}}
	if !hasCollectedField(ctx, edgesField) || first != nil && *first == 0 || last != nil && *last == 0 {
		if hasCollectedField(ctx, totalCountField) ||
			hasCollectedField(ctx, pageInfoField) {
			count, err := t.Count(ctx)
			if err != nil {
				return nil, err
			}
			conn.TotalCount = count
			conn.PageInfo.HasNextPage = first != nil && count > 0
			conn.PageInfo.HasPreviousPage = last != nil && count > 0
		}
		return conn, nil
	}

	if (after != nil || first != nil || before != nil || last != nil) && hasCollectedField(ctx, totalCountField) {
		count, err := t.Clone().Count(ctx)
		if err != nil {
			return nil, err
		}
		conn.TotalCount = count
	}

	t = pager.applyCursors(t, after, before)
	t = pager.applyOrder(t, last != nil)
	var limit int
	if first != nil {
		limit = *first + 1
	} else if last != nil {
		limit = *last + 1
	}
	if limit > 0 {
		t = t.Limit(limit)
	}

	if field := getCollectedField(ctx, edgesField, nodeField); field != nil {
		t = t.collectField(graphql.GetOperationContext(ctx), *field)
	}

	nodes, err := t.All(ctx)
	if err != nil || len(nodes) == 0 {
		return conn, err
	}

	if len(nodes) == limit {
		conn.PageInfo.HasNextPage = first != nil
		conn.PageInfo.HasPreviousPage = last != nil
		nodes = nodes[:len(nodes)-1]
	}

	var nodeAt func(int) *Test
	if last != nil {
		n := len(nodes) - 1
		nodeAt = func(i int) *Test {
			return nodes[n-i]
		}
	} else {
		nodeAt = func(i int) *Test {
			return nodes[i]
		}
	}

	conn.Edges = make([]*TestEdge, len(nodes))
	for i := range nodes {
		node := nodeAt(i)
		conn.Edges[i] = &TestEdge{
			Node:   node,
			Cursor: pager.toCursor(node),
		}
	}

	conn.PageInfo.StartCursor = &conn.Edges[0].Cursor
	conn.PageInfo.EndCursor = &conn.Edges[len(conn.Edges)-1].Cursor
	if conn.TotalCount == 0 {
		conn.TotalCount = len(nodes)
	}

	return conn, nil
}

// TestOrderField defines the ordering field of Test.
type TestOrderField struct {
	field    string
	toCursor func(*Test) Cursor
}

// TestOrder defines the ordering of Test.
type TestOrder struct {
	Direction OrderDirection  `json:"direction"`
	Field     *TestOrderField `json:"field"`
}

// DefaultTestOrder is the default ordering of Test.
var DefaultTestOrder = &TestOrder{
	Direction: OrderDirectionAsc,
	Field: &TestOrderField{
		field: test.FieldID,
		toCursor: func(t *Test) Cursor {
			return Cursor{ID: t.ID}
		},
	},
}

// ToEdge converts Test into TestEdge.
func (t *Test) ToEdge(order *TestOrder) *TestEdge {
	if order == nil {
		order = DefaultTestOrder
	}
	return &TestEdge{
		Node:   t,
		Cursor: order.Field.toCursor(t),
	}
}
